# SPDX-License-Identifier: GPL-2.0
# Sophgo Platform Support
obj-$(CONFIG_SND_SOC_CV1800B_TDM) += cv1800b_tdm.o
obj-$(CONFIG_SND_SOC_CV1800B_SOUND_CARD) += cv1800b_sound_card.o
obj-$(CONFIG_SND_SOC_CV1800B_ADC_CODEC) += cv1800b_sound_adc.o